version: 2
sources:
  - name: raw_fx_rates_usd_base
    schema: main
    tables:
      - name: raw_fx_rates_usd_base
        columns:
          - name: timestamp
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: integer
              - dbt_utils.expression_is_true:
                  expression: "{{ column_name }} <= epoch(now())"
          - name: currency
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_value_lengths_to_equal:
                  value: 3
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: varchar
          - name: rate
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
              - dbt_expectations.expect_column_values_to_be_of_type:
                  column_type: double